In [20]:
import pandas as pd
data = pd.read_csv("bajaj_loans_raw.csv")

In [21]:
# load the data ---> csv/excel/ database --> JSON -->text

# display 

data.head(4)

,customer_id,name,age,city,employment_type,annual_income,loan_amount,loan_purpose,tenure_months,emi,credit_score,status,application_date
0,BF0177,Customer_177,59,JAIPUR,Salaried,64764.0,"428,387",Debt Consolidation,24,14993,765.0,Pending,15-09-2023
1,BF0133,Customer_133,49,Chennai,Freelancer,123142.0,126218,Home Renovation,12,4417,673.0,Approved,13-07-2023
2,BF0007,Customer_7,32,Chennai,Salaried,198420.0,"926,906",Travel,24,32441,792.0,Approved,09-01-2023
3,BF0085,Customer_85,54,Bangalore,Self-Employed,45159.0,"1,345,302",Wedding,36,47085,756.0,Approved,03-05-2023

In [39]:
# rename the columns
data.rename({
    'employment_type':'employment type'
}, axis=1, inplace=True) #

In [40]:
data.head(2)

,customer_id,name,age,city,employment type,annual_income,loan_amount,loan_purpose,tenure_months,emi,credit_score,status,application_date
0,BF0177,Customer_177,59,JAIPUR,Salaried,64764.0,"428,387",Debt Consolidation,24,14993,765.0,Pending,15-09-2023
1,BF0133,Customer_133,49,Chennai,Freelancer,123142.0,126218,Home Renovation,12,4417,673.0,Approved,13-07-2023

In [45]:
data['employment type'].value_counts()

employment type
Business         133
Salaried         131
Freelancer       117
Self-Employed    117
Name: count, dtype: int64

In [44]:
data['city'].value_counts()

city
Bangalore    53
Jaipur       52
Ahmedabad    51
Hyderabad    51
Mumbai       49
Delhi        48
Chennai      47
Pune         34
MUMBAI       18
delhi        13
chennai      13
mumbai       11
DELHI        11
bangalore     9
CHENNAI       9
BANGALORE     9
JAIPUR        7
HYDERABAD     7
ahmedabad     6
AHMEDABAD     6
hyderabad     5
PUNE          4
pune          3
jaipur        2
Name: count, dtype: int64

In [43]:
data.describe(include='all')

,customer_id,name,age,city,employment type,annual_income,loan_amount,loan_purpose,tenure_months,emi,credit_score,status,application_date
count,518,518,518.000000,518,498,472.000000,518,503,518.000000,518.000000,487.000000,518,518
unique,500,500,NaN,24,4,NaN,500,7,NaN,NaN,NaN,9,500
top,BF0083,Customer_83,NaN,Bangalore,Business,NaN,1245889,Wedding,NaN,NaN,NaN,Approved,30-04-2023
freq,2,2,NaN,53,133,NaN,2,80,NaN,NaN,NaN,291,2
mean,NaN,NaN,44.880309,NaN,NaN,113090.398305,NaN,NaN,36.324324,27246.905405,696.620123,NaN,NaN
std,NaN,NaN,60.967578,NaN,NaN,51305.647595,NaN,NaN,17.049338,14061.914462,71.391558,NaN,NaN
min,NaN,NaN,-5.000000,NaN,NaN,25235.000000,NaN,NaN,12.000000,1754.000000,462.000000,NaN,NaN
25%,NaN,NaN,31.000000,NaN,NaN,68249.250000,NaN,NaN,24.000000,15597.000000,648.000000,NaN,NaN
50%,NaN,NaN,42.000000,NaN,NaN,113164.000000,NaN,NaN,36.000000,26856.000000,697.000000,NaN,NaN
75%,NaN,NaN,51.000000,NaN,NaN,157400.500000,NaN,NaN,48.000000,39423.000000,748.000000,NaN,NaN
max,NaN,NaN,999.000000,NaN,NaN,199944.000000,NaN,NaN,60.000000,52214.000000,884.000000,NaN,NaN

In [ ]:
data.describe(include='o')

# basic stats 
# numerical value ==?
age -> min, max , avg ( mean)

              age  annual_income  tenure_months           emi  credit_score
count  518.000000     472.000000     518.000000    518.000000    487.000000
mean    44.880309  113090.398305      36.324324  27246.905405    696.620123
std     60.967578   51305.647595      17.049338  14061.914462     71.391558
min     -5.000000   25235.000000      12.000000   1754.000000    462.000000
25%     31.000000   68249.250000      24.000000  15597.000000    648.000000
50%     42.000000  113164.000000      36.000000  26856.000000    697.000000
75%     51.000000  157400.500000      48.000000  39423.000000    748.000000
max    999.000000  199944.000000      60.000000  52214.000000    884.000000

In [47]:
# method 1 :# selection of columns ?? only columns
type(data['age'] )
# data['employment_type'].describe()

#v method 2
# data.employment type

# loading the data
# and in data -->col--> like data['marks in board']

pandas.Series

In [31]:
data.shape

(518, 13)

In [30]:
data.tail(5)

,customer_id,name,age,city,employment_type,annual_income,loan_amount,loan_purpose,tenure_months,emi,credit_score,status,application_date
513,BF0072,Customer_72,22,Pune,Freelancer,144156.0,702026,Business,36,24570,711.0,Approved,14-04-2023
514,BF0107,Customer_107,26,MUMBAI,Self-Employed,NaN,638365,Debt Consolidation,48,22342,803.0,Approved,05-06-2023
515,BF0271,Customer_271,40,Mumbai,Salaried,NaN,"549,137",Education,60,19219,756.0,Approved,30-01-2024
516,BF0436,Customer_436,57,MUMBAI,NaN,92728.0,"883,032",Education,24,30906,784.0,Approved,28-09-2024
517,BF0103,Customer_103,58,Hyderabad,Business,154473.0,647135,Debt Consolidation,36,22649,701.0,Approved,30-05-2023

In [6]:
type(data)

pandas.DataFrame

In [ ]:
# select top 5 * from table

data.head(5)

,customer_id,name,age,city,employment_type,annual_income,loan_amount,loan_purpose,tenure_months,emi,credit_score,status,application_date
0,BF0177,Customer_177,59,JAIPUR,Salaried,64764.0,"428,387",Debt Consolidation,24,14993,765.0,Pending,15-09-2023
1,BF0133,Customer_133,49,Chennai,Freelancer,123142.0,126218,Home Renovation,12,4417,673.0,Approved,13-07-2023
2,BF0007,Customer_7,32,Chennai,Salaried,198420.0,"926,906",Travel,24,32441,792.0,Approved,09-01-2023
3,BF0085,Customer_85,54,Bangalore,Self-Employed,45159.0,"1,345,302",Wedding,36,47085,756.0,Approved,03-05-2023
4,BF0457,Customer_457,56,Pune,Freelancer,165518.0,292615,Travel,36,10241,NaN,Approved,29-10-2024

In [8]:
data.tail(3)

,customer_id,name,age,city,employment_type,annual_income,loan_amount,loan_purpose,tenure_months,emi,credit_score,status,application_date
515,BF0271,Customer_271,40,Mumbai,Salaried,NaN,"549,137",Education,60,19219,756.0,Approved,30-01-2024
516,BF0436,Customer_436,57,MUMBAI,NaN,92728.0,"883,032",Education,24,30906,784.0,Approved,28-09-2024
517,BF0103,Customer_103,58,Hyderabad,Business,154473.0,647135,Debt Consolidation,36,22649,701.0,Approved,30-05-2023

In [10]:
# select top 5 customer_id, name, age from data

data[['customer_id','name','age','city']].head(5)

  customer_id          name  age       city
0      BF0177  Customer_177   59     JAIPUR
1      BF0133  Customer_133   49    Chennai
2      BF0007    Customer_7   32    Chennai
3      BF0085   Customer_85   54  Bangalore
4      BF0457  Customer_457   56       Pune

In [11]:
type(data)

pandas.DataFrame

In [12]:
type(data[['customer_id','name','age','city']])

pandas.DataFrame

In [14]:
type(data['customer_id'])

pandas.Series

In [16]:
data[['customer_id','name','age','city']].describe()

              age
count  518.000000
mean    44.880309
std     60.967578
min     -5.000000
25%     31.000000
50%     42.000000
75%     51.000000
max    999.000000

In [19]:
# filter ??
# select * from data where age ==999

data[data['age']==-5]

,customer_id,name,age,city,employment_type,annual_income,loan_amount,loan_purpose,tenure_months,emi,credit_score,status,application_date
337,BF0243,Customer_243,-5,Jaipur,Salaried,76745.0,71172,Medical Emergency,48,2491,548.0,Approved,21-12-2023
342,BF0036,Customer_36,-5,Ahmedabad,Freelancer,53016.0,1273975,Home Renovation,36,44589,711.0,Pending,21-02-2023
474,BF0240,Customer_240,-5,Jaipur,Salaried,129680.0,"1,083,578",Education,60,37925,636.0,Approved,16-12-2023

In [17]:
data

,customer_id,name,age,city,employment_type,annual_income,loan_amount,loan_purpose,tenure_months,emi,credit_score,status,application_date
0,BF0177,Customer_177,59,JAIPUR,Salaried,64764.0,"428,387",Debt Consolidation,24,14993,765.0,Pending,15-09-2023
1,BF0133,Customer_133,49,Chennai,Freelancer,123142.0,126218,Home Renovation,12,4417,673.0,Approved,13-07-2023
2,BF0007,Customer_7,32,Chennai,Salaried,198420.0,"926,906",Travel,24,32441,792.0,Approved,09-01-2023
3,BF0085,Customer_85,54,Bangalore,Self-Employed,45159.0,"1,345,302",Wedding,36,47085,756.0,Approved,03-05-2023
4,BF0457,Customer_457,56,Pune,Freelancer,165518.0,292615,Travel,36,10241,NaN,Approved,29-10-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,BF0072,Customer_72,22,Pune,Freelancer,144156.0,702026,Business,36,24570,711.0,Approved,14-04-2023
514,BF0107,Customer_107,26,MUMBAI,Self-Employed,NaN,638365,Debt Consolidation,48,22342,803.0,Approved,05-06-2023
515,BF0271,Customer_271,40,Mumbai,Salaried,NaN,"549,137",Education,60,19219,756.0,Approved,30-01-2024
516,BF0436,Customer_436,57,MUMBAI,NaN,92728.0,"883,032",Education,24,30906,784.0,Approved,28-09-2024
517,BF0103,Customer_103,58,Hyderabad,Business,154473.0,647135,Debt Consolidation,36,22649,701.0,Approved,30-05-2023

In [48]:
data.columns

Index(['customer_id', 'name', 'age', 'city', 'employment type',
       'annual_income', 'loan_amount', 'loan_purpose', 'tenure_months', 'emi',
       'credit_score', 'status', 'application_date'],
      dtype='str')

In [49]:
# data' data dtypes
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 518 entries, 0 to 517
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       518 non-null    str
 1   name              518 non-null    str
 2   age               518 non-null    int64
 3   city              518 non-null    str
 4   employment type   498 non-null    str
 5   annual_income     472 non-null    float64
 6   loan_amount       518 non-null    str
 7   loan_purpose      503 non-null    str
 8   tenure_months     518 non-null    int64
 9   emi               518 non-null    int64
 10  credit_score      487 non-null    float64
 11  status            518 non-null    str
 12  application_date  518 non-null    str
dtypes: float64(2), int64(3), str(8)
memory usage: 52.7 KB

In [51]:
data.isnull().sum()

customer_id          0
name                 0
age                  0
city                 0
employment type     20
annual_income       46
loan_amount          0
loan_purpose        15
tenure_months        0
emi                  0
credit_score        31
status               0
application_date     0
dtype: int64

In [ ]:
# filter
# condtion = 
# tell me avg income where eomplyment type is null
df = data[data['employment type'].isnull()]

In [63]:
df['annual_income'].describe()

count        19.000000
mean     107034.789474
std       48633.084328
min       28709.000000
25%       71903.000000
50%      104767.000000
75%      148593.500000
max      184096.000000
Name: annual_income, dtype: float64

In [69]:
# in interview

data = {
    'customer_id': ['BF001', 'BF002', 'BF003', 'BF004', 'BF005'],
    'age':         [28, 35, 42, 24, 31],
    'loan_amount': [250000, 500000, 150000, 750000, 320000],
    'emi':         [8500, 15200, 5100, 22000, 10500],
    'credit_score':[720, 680, 790, 610, 745],
    'city':        ['Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Pune'],
    'status':      ['Approved', 'Approved', 'Rejected', 'Pending', 'Approved']
}

# create the dataframe
df = pd.DataFrame(data)


#city wise --> avg loan amount
df[df.city=='Mumbai']['loan_amount'].mean()

np.float64(500000.0)

In [73]:
def avg_valu_cal(df, column_name, city,avg_column_name):
    df1 = df[df[column_name]==city]
    result = df1[avg_column_name].mean()
    return result

avg_valu_cal(df,'city','Mumbai','loan_amount')

np.float64(500000.0)

In [77]:
output = {}
for i in df['city']:
    output[i] = avg_valu_cal(df,'city',i,'loan_amount')

output

{'Mumbai': np.float64(500000.0),
 'Pune': np.float64(410000.0),
 'Delhi': np.float64(150000.0)}

In [74]:
df.head()

  customer_id  age  loan_amount    emi  credit_score    city    status
0       BF001   28       250000   8500           720  Mumbai  Approved
1       BF002   35       500000  15200           680    Pune  Approved
2       BF003   42       150000   5100           790   Delhi  Rejected
3       BF004   24       750000  22000           610  Mumbai   Pending
4       BF005   31       320000  10500           745    Pune  Approved

In [90]:

data = {
    'customer_id': ['BF001', 'BF002', 'BF003', 'BF004', 'BF005'],
    'age':         [28, 35, 42, 24, 31],
    'loan_amount': [250000, 500000, 150000, 750000, 320000],
    'emi':         [8500, 15200, 5100, 22000, 10500],
    'credit_score':[720, 680, 790, 610, 745],
    'city':        ['Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Pune'],
    'status':      ['Approved', 'Approved', 'Rejected', 'Approved', 'Approved']
}

df = pd.DataFrame(data)
df.shape

# # tell what is approval rate city wise ??
# df.city.value_counts()
# # approval rate --> % 2/5
# 2/5

(5, 7)

In [94]:
(df[(df.city=='Delhi') & (df.status=='Approved')].shape[0])/len(df)*100

0.0

In [80]:
df.shape

(5, 7)

In [99]:
# pandas --> data problem --dict --> csv --> 
# describe, info, isnull, filter data ( applyijg the conditon ) 
# groupby 

df.groupby('city').agg({
    'loan_amount':['mean','max','sum']
})

       loan_amount
              mean     max      sum
city
Delhi     150000.0  150000   150000
Mumbai    500000.0  750000  1000000
Pune      410000.0  500000   820000